apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: stdio-accesslog
  namespace: istio-system
spec:
  match: context.protocol == "http" || context.protocol == "grpc"
  actions:
  - handler: stdio
    instance:
    - accesslog