apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: accesslog
  namespace: istio-system
spec:
  compiledTemplate: logentry
  params:
    severity: '"Default"'
    timestamp: request.time
    variables:
      sourceIp: source.ip | ip("0.0.0.0")
      destinationIp: destination.ip | ip("0.0.0.0")
      sourceUser: source.principal | ""
      method: request.method | ""
      url: request.path | ""
      protocol: request.scheme | "http"
      responseCode: response.code | 0
      responseSize: response.size | 0
      requestSize: request.size | 0
      latency: response.duration | "0ms"
    monitored_resource_type: '"UNSPECIFIED"'
